name: ShellCheckTest

on:
  pull_request:

jobs:
  shell_check_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/problem-matcher
            bash

      - name: Add Problem Matcher
        shell: bash
        run: echo "::add-matcher::.github/problem-matcher/shellcheck.json"

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './bash'
       
